package jdby.sample.sql;

import jdby.core.QueryBuilder;
import jdby.core.RowConnection;
import jdby.core.Batch;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;

import static jdby.core.Query.builder;
import static jdby.core.Query.sql;
import static jdby.core.SqlParameter.*;

public class SqlDao {

    private final RowConnection connection;

    public SqlDao(RowConnection connection) {
        this.connection = connection;
    }

    public void createSchema() throws SQLException {
        sql(
            """
                create table if not exists users (
                  id int generated by default as identity primary key,
                  full_name varchar(100) not null,
                  dob date,
                  last_login timestamp with time zone
                )
                """
        ).executeUpdate(connection);
    }

    public List<UserRow> listAllUsers() throws SQLException {
        return sql(
            """
                select id, full_name, dob, last_login
                  from users
                order by full_name
                """
        ).listRows(connection, UserRow.class);
    }

    public List<UserRow> listUsersByFilter(String nameMask, LocalDate birthdayFrom, LocalDate birthdayTo) throws SQLException {
        QueryBuilder buf = builder(
            """
                select id, full_name, dob, last_login
                  from users
                 where 1 = 1
                """
        );
        if (nameMask != null) {
            buf.append("and full_name like ?", pString(nameMask));
        }
        if (birthdayFrom != null) {
            buf.append("and dob >= ?", pDate(birthdayFrom));
        }
        if (birthdayTo != null) {
            buf.append("and dob <= ?", pDate(birthdayTo));
        }
        buf.append("order by full_name");
        return buf.toQuery().listRows(connection, UserRow.class);
    }

    public Integer insertUser(String name, LocalDate birthday) throws SQLException {
        return sql(
            """
                insert into users (full_name, dob) values (?, ?)
                """,
            pString(name), pDate(birthday)
        ).executeUpdate(connection, Integer.class, "id");
    }

    public void setLastLogin(int id, OffsetDateTime lastLogin) throws SQLException {
        sql(
            """
                update users set last_login = ? where id = ?
                """,
            pDateTime(lastLogin), pInt(id)
        ).executeUpdate(connection);
    }

    public UserRow maybeUser(int id) throws SQLException {
        return sql(
            """
                select id, full_name, dob, last_login
                  from users
                 where id = ?
                """,
            pInt(id)
        ).maybeRow(connection, UserRow.class);
    }

    public UserRow loadUser(int id) throws SQLException {
        return sql(
            """
                select id, full_name, dob, last_login
                  from users
                 where id = ?
                """,
            pInt(id)
        ).exactlyOneRow(connection, UserRow.class);
    }

    public void batchAddUser(Batch batch, String name, LocalDate birthday) throws SQLException {
        batch.addBatch(connection, sql(
            """
                insert into users (full_name, dob) values (?, ?)
                """,
            pString(name), pDate(birthday)
        ));
    }
}
