package jdby.sample.dao;

import jdby.core.Batch;
import jdby.dao.SqlBuilder;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;

import static jdby.dao.SqlCommands.*;

public interface SqlDao {

    default void createSchema() throws SQLException {
        executeUpdate(
            """
                create table if not exists users (
                  id int generated by default as identity primary key,
                  full_name varchar(100) not null,
                  dob date,
                  last_login timestamp with time zone
                )
                """
        );
    }

    default List<UserRow> listAllUsers() throws SQLException {
        return listRows(
            """
                select id, full_name, dob, last_login
                  from users
                order by full_name
                """
        );
    }

    default List<UserRow> listUsersByFilter(String nameMask, LocalDate birthdayFrom, LocalDate birthdayTo) throws SQLException {
        SqlBuilder buf = builder(
            """
                select id, full_name, dob, last_login
                  from users
                 where 1 = 1
                """
        );
        if (nameMask != null) {
            buf.append("and full_name like :nameMask");
        }
        if (birthdayFrom != null) {
            buf.append("and dob >= :birthdayFrom");
        }
        if (birthdayTo != null) {
            buf.append("and dob <= :birthdayTo");
        }
        buf.append("order by full_name");
        return listRows(buf);
    }

    default Integer insertUser(String name, LocalDate birthday) throws SQLException {
        return insertRow(
            "id",
            """
                insert into users (full_name, dob) values (:name, :birthday)
                """
        );
    }

    default void setLastLogin(int id, OffsetDateTime lastLogin) throws SQLException {
        executeUpdate(
            """
                update users set last_login = :lastLogin where id = :id
                """
        );
    }

    default UserRow maybeUser(int id) throws SQLException {
        return maybeRow(
            """
                select id, full_name, dob, last_login
                  from users
                 where id = :id
                """
        );
    }

    default UserRow loadUser(int id) throws SQLException {
        return exactlyOneRow(
            """
                select id, full_name, dob, last_login
                  from users
                 where id = :id
                """
        );
    }

    default void batchAddUser(Batch batch, String name, LocalDate birthday) throws SQLException {
        executeBatch(
            batch,
            """
                insert into users (full_name, dob) values (:name, :birthday)
                """
        );
    }
}
